### ISSUE TITLE
Example are out of date?

### ISSUE THREAD

**Issue by erwanvivien** [Waayway/windows-volume-control#2]
Hello 👋 

Thanks for your work, I'm interested in this crate, but I found the examples to be out of date?
Also, I think this doesn't give the realtime sound volume, how could I get this information?

**Comment by Waayway** [comment]
Hey,
I've personally made it just to control the volume of applications. I think the getVolume function actually gets the volume of the program but it isn't actual volume that being outputted since that's not what i made this for.

**Comment by erwanvivien** [comment]
Thanks for your answer about the actual outputted volume!
For the examples, do you have the same problem I encountered?

**Comment by Waayway** [comment]
No i don't have any problems with the example. I think the issue you're describing is something different from what this lib does... it is basically a api for interacting with the windows volume mixer via rust it does nothing with any sound.

**Comment by erwanvivien** [comment]
Ah indeed, I think I had a different `windows` version, with 0.44 it works just fine!
Sorry for bothering!
