### ISSUE TITLE
Issue with setVolume

### ISSUE THREAD

**Issue by ValgulNecron** [Waayway/windows-volume-control#3]
Hi i tried setting the song with "setVolume" function with 1.0 as input it set the volume to 100% but does not unmute the device if it were muted before is that normal? and how can i unmute it with your crate?

**Comment by Waayway** [comment]
HI, The volume does change but it stays muted. Theres a function called setMute(bool) which you could use to change if something is muted or not. Hope this helps!

**Comment by ValgulNecron** [comment]
Hi, thanks this would really help but it seem like in version 0.1.0 on docs.rs and by adding it with cargo add windows-volume-control  the setMute and getMute are not there but in the github src/session.rs it does exist

**Comment by Waayway** [comment]
Yes i do see that... I've not been working on this lib for quite a while will see if i can push it to crates.io new version 0.1.1

**Comment by Waayway** [comment]
It Should now be on crates.io
