### ISSUE TITLE
How to changeing microphone volume with the crate ?

### ISSUE THREAD

**Issue by tu6ge** [Waayway/windows-volume-control#5]
In the past few days, I have been searching for an API in windows crate that can change the microphone volume, but I haven't found it yet. Your crate has given me some hope, but I am still quite confused

**Comment by Waayway** [comment]
Hi, i've made this crate for output volumes per program not for microphones, it just using the windows api. if you still need output volume you could extend the lib.

**Comment by Waayway** [comment]
see pull request #4 it has something about input devices

**Comment by tu6ge** [comment]
Thank you very much for providing the idea. I think I found the way ...
