### ISSUE TITLE
ERROR: Couldn't initialize windows connection: 无法在设置线程模式后对其加以更改。 (0x80010106) [0921/024011.459:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412 error Command failed with exit code 4294967295. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### ISSUE THREAD

**Issue by keyboard2005** [Waayway/windows-volume-control#7]
ERROR: Couldn't initialize windows connection: 无法在设置线程模式后对其加以更改。 (0x80010106)
[0921/024011.459:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

mycode >>>>

#[command]
fn get_system_volume() -> Result<f32, String> {
    unsafe {
        let mut controller = AudioController::init(None);
        controller.GetSessions();
        controller.GetDefaultAudioEnpointVolumeControl();
        controller.GetAllProcessSessions();
        let test = controller.get_all_session_names();
        let master_session = controller.get_session_by_name("master".to_string());
        println!("{:?}",master_session.unwrap().getVolume());
        Ok(master_session.unwrap().getVolume())
    }
}

**Comment by Waayway** [comment]
Hey, sorry for the late reply... i don't think this is an issue of this library. Are you trying to run this in wasm? It doesn't support wasm.
